FROM oven/bun:1.3.2-alpine

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN rm -rf node_modules && \
    bun install

RUN apk add --no-cache wget

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

CMD ["bun", "--hot", "dev", "--port", "8080", "--host"]
