FROM oven/bun:1.3.2-alpine

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN rm -rf node_modules && \
    bun install

EXPOSE 8080

CMD ["bun", "--hot", "dev", "--port", "8080", "--host"]
